# Use c since we provide own build tools
language: c
dist: trusty
sudo: false

notifications:
  email: false

branches:
  only:
  - develop

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack build
  - stack exec site build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep-history: true
  local_dir: _site/
  target-branch: gh-pages
  on:
    branch: master
